version: '3.8'

services:
   db:
      image: mysql:8.0
      container_name: mysql_server
      volumes: 
         - ./tmp/db:/var/lib/mysql
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
       - '8001:80'
      environment:
        PMA_HOST: db  